#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterBarang018
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuizMahasiswa")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::MasterBarang018.Properties.Settings.Default.QuizMahasiswaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_barang> tbl_barangs
		{
			get
			{
				return this.GetTable<tbl_barang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_barang")]
	public partial class tbl_barang
	{
		
		private int _id_barang;
		
		private string _nama_barang;
		
		private System.Nullable<int> _harga;
		
		private System.Nullable<int> _stok;
		
		private System.Nullable<int> _nama_supplier;
		
		public tbl_barang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_barang", DbType="Int NOT NULL")]
		public int id_barang
		{
			get
			{
				return this._id_barang;
			}
			set
			{
				if ((this._id_barang != value))
				{
					this._id_barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this._nama_barang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harga", DbType="Int")]
		public System.Nullable<int> harga
		{
			get
			{
				return this._harga;
			}
			set
			{
				if ((this._harga != value))
				{
					this._harga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stok", DbType="Int")]
		public System.Nullable<int> stok
		{
			get
			{
				return this._stok;
			}
			set
			{
				if ((this._stok != value))
				{
					this._stok = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_supplier", DbType="Int")]
		public System.Nullable<int> nama_supplier
		{
			get
			{
				return this._nama_supplier;
			}
			set
			{
				if ((this._nama_supplier != value))
				{
					this._nama_supplier = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
